Makefile, app/api/user.py, app/model/user.py, app/model/util/id.py, app/util/flask_common.py, requirements.txt, tests/api/test_user.py
1. Refactor into flask common
2. Remove uneccessary tests
3. Change user id to be a uuid string
=> Refactor user api

app/api/user/main.py, app/model/user.py, tests/api/user/test_user.py
for issue https://github.com/Ragil/Communicate-Indonesia/issues/19
=> Add district restriction to farmers

app/model/config.py, app/util/flask_common.py, tests/api/user/test_user.py
Fixed user auth:
1. Removed unnecessary info for invalid api key
2. Added admin name property in Config model
3. Removed toJson method in Config
=> Fix user auth

app.yaml, app/api/config/__init__.py, app/api/config/main.py, app/model/config.py, app/util/flask_common.py, tests/api/config/test_config.py
=> Config update

app/api/config/main.py, app/model/config.py, tests/api/config/test_config.py
=> Removed basic auth for config and required key

app/api/sms/harvest_action.py, app/api/sms/plant_action.py, tests/api/sms/test_harvest_command.py
=> Implement harvest action and command

app/api/sms/main.py, app/command/base.py, tests/api/sms/test_sms.py, tests/command/test_dispatcher.py
The user now recieves an sms when the system cannot match their request to a command
=> Fix route error handling on dispatcher error.

app/api/sms/harvest_action.py, tests/api/sms/test_harvest_command.py
Fixed #31 : Removed district_id, exception, return, aligned with dispatcher.
=> Fix harvest action command

app/api/sms/harvest_action.py
=> Fixed to single user

app/api/sms/sell_action.py, tests/api/sms/test_sell_command.py
=> Implement sell action

app/api/sms/plant_action.py, tests/api/sms/test_plant_command.py
=> Implement plant action for single user, tested

app/api/sms/harvest_action.py, app/api/sms/main.py, app/api/sms/plant_action.py, app/api/sms/sell_action.py, app/i18n/i18n.py, tests/api/sms/test_harvest_command.py, tests/api/sms/test_plant_command.py, tests/api/sms/test_sell_command.py, tests/api/sms/test_sms.py
=> Added SMS response for unknown and successful commands

app/api/sms/base_action.py, app/api/sms/query_action.py, app/i18n/i18n.py, tests/api/sms/test_query_command.py
=> Query district

app/api/sms/query_action.py, app/i18n/i18n.py, tests/api/combined/test_combined_sms.py, tests/api/sms/test_query_command.py, tests/i18n/test_i18n.py
=> Integration sms

app/api/sms/harvest_action.py, app/api/sms/main.py, app/api/sms/plant_action.py, app/command/base.py, tests/api/combined/test_combined_sms.py, tests/api/sms/test_plant_command.py
=> Fix integration sms

app.yaml, app/api/sms/broadcast.py, app/api/sms/broadcast_action.py, app/api/sms/main.py, app/i18n/i18n.py, queue.yaml, tests/api/sms/test_broadcast_command.py, tests/api/sms/test_sell_command.py
=> Broadcast queue

app/api/sms/harvest_action.py
=> Fix integration sms double ndb access

app/api/sms/sell_action.py, app/i18n/i18n.py, tests/api/sms/test_sell_action.py, tests/api/sms/test_sell_command.py, tests/api/test_sms_api.py
=> Fixed sell action to subtract harvested plants

app/api/sms/broadcast_action.py, app/api/sms/broadcast_worker.py, app/i18n/i18n.py, tests/api/sms/test_broadcast_action.py, tests/api/sms/test_broadcast_command.py, tests/api/sms/test_broadcast_worker.py
Fix for #59 (multiwords district)
=> Fix broadcast sms: multiwords district, mock twilio

app/api/sms/harvest_action.py, app/api/sms/plant_action.py, app/api/sms/sell_action.py, tests/api/sms/test_harvest_command.py, tests/api/sms/test_plant_command.py, tests/api/sms/test_sell_command.py
=> Fix cmd cases

app/api/sms/main.py, app/i18n/i18n.py, tests/api/sms/test_sms.py
=> Added valid cmd and formatting res to unknown cmd
